### ISSUE TITLE
Set up Flask Environment

### ISSUE THREAD

**Issue by YayunFan** [nyudevops-recommendation/recommendations#1]
**As a** developer
**I need** a virtual common environment for all team member to use
**So that** we can work remotely and all our code will be compatible and can be merged without issue

Assumptions:
* We will set up a vagrant file to use a Linux setup using Vagrant and VirtualBox.
* We will use Python with Flask to develop the project.

Acceptance Criteria:
```
When I type "vagrant up" while in the directory of a cloned repository
I should have access to a full virtual environment where i can use Flask.
```

**Comment by hi348** [comment]
Was the vagrant file addition reverted? If so, can I move this back into the backlog?

**Comment by qijinze911** [comment]
I reverted it since I merge it with mainline. I have already do it again. It's now in my fork. If all people approve that we can merge into mainline.

**Comment by cheryl1223** [comment]
The Vagrant file you pushed is an empty Vagrant init file. Please use https://github.com/nyu-devops/lab-flask-rest/blob/master/Vagrantfile instead.
