### ISSUE TITLE
Refactor CREATE API using Flask-RESTPlus and add corresponding Swagger Docs

### ISSUE THREAD

**Issue by YayunFan** [nyudevops-recommendation/recommendations#106]
**As a** developer
**I need** swagger doc for CREATE API
**So that** I can check the API more easily

**Assumptions:** 
* refactor will not break anything

**Acceptance Criteria:**
```
Given the refactored service
When visit the link to swagger doc for CREATE API
Then I can get the doc for CREATE API
```

**Comment by hi348** [comment]
See the read refactor issue for details. I did them both together.
