### ISSUE TITLE
Design the database

### ISSUE THREAD

**Issue by cheryl1223** [nyudevops-recommendation/recommendations#15]
**As a** developer
**I need** database
**So that** I can store and get my resources

**Assumptions:** 
* Use SQLAlchemy for completing an MVP

**Acceptance Criteria:**
```
the database will provide all data we need for completing the recommendation service
```

**Comment by hi348** [comment]
So far: records will have RecID, ProdID1, ProdID2, RecType
Primary Key is just RedID

**Comment by hi348** [comment]
Also a "success" field if we decide to implement the counter as our action.
