### ISSUE TITLE
Plan for Sprint 1

### ISSUE THREAD

**Issue by hi348** [nyudevops-recommendation/recommendations#19]
**As a** agile team
**I need** set up all stories for sprint 1
**So that** I know what to do for any given task in order to make progress towards project completion.

**Assumptions:** 
* We can use the examples from class to guide us on how to construct stories and to give us hints about what stories are needed.
* We can also use the HW document to get ideas about what stories to write.

**Acceptance Criteria:**
```
When the team is asked "Are we missing anything for our planning phase?"
We should be able to answer "no."
And when asked "Do we know exactly how to proceed for sprint 1?"
We should be able to say "yes."
```

**Comment by hi348** [comment]
We can move this to review or done when all the stories are completed and sorted. I am still seeing some stories that are not done.

**Comment by cheryl1223** [comment]
changed the verb "complete" to "plan", as we only planned for what we are going to do, using complete is kind of confusing here. BTW I like your way of writing the acceptance criteria :smiley:
