### ISSUE TITLE
Implement "Success" Action API

### ISSUE THREAD

**Issue by hi348** [nyudevops-recommendation/recommendations#22]
**As a** user  
**I need** a way to determine how successful each recommendation is  
**So that** I can determine how effective my model is for determining relationships  

**Assumptions:** 
* Success can be measured by a counter that tracks sales. So each time a recommendation is listed and results in a sale of the recommended product to that customer, the counter should be incremented.

**Acceptance Criteria:**
```
When I call HTTP PUT /recommendations/{rec-id}/success
The success counter should be incremented for RecID
```

**Comment by qijinze911** [comment]
Hello Harrysh, I try to make this API, but I find I cannot understand this API's function. Could you make this by yourself?

**Comment by hi348** [comment]
Sure, I'll try.
