### ISSUE TITLE
Add a Travis CI badge

### ISSUE THREAD

**Issue by qijinze911** [nyudevops-recommendation/recommendations#56]
**As a** developer
**I need** Travis CI badge cover
**So that** I can see how the code is going 

**Assumptions:** 
* Use Travis CI badge to see the code is going well

**Acceptance Criteria:**
```
Given using Travis CI badge
When open README.md
Then we can see our code coverage
```

**Comment by cheryl1223** [comment]
the test coverage badge shows unknown on my side. could you please change the link to your Travis but to the organization instead?
