### ISSUE TITLE
Create IBM Cloud Organization

### ISSUE THREAD

**Issue by hi348** [nyudevops-recommendation/recommendations#57]
**As a** Developer
**I need** a cloud account  
**So that** I can deploy our program onto said coud.

**Assumptions:** 
* We will be using IBM Cloud

**Acceptance Criteria:**
```
When I try to log in
Then I should be logged in
```

**Comment by hi348** [comment]
The reason I put this into review is because I want everyone to confirm that the invitation gives them proper access. If not I might have to go back and add extra permissions. I kept everything default when I created the group and added users so hopefully that is sufficient.

**Comment by cheryl1223** [comment]
how to check if I have access to this application on IBM Cloud?

**Comment by hi348** [comment]
Not sure how the interface works on the invitee side. Maybe we can only confirm once we start deploying?

**Comment by hi348** [comment]
I just created the flask app. Maybe checking if that is visible will by default confirm that you have access.

**Comment by cheryl1223** [comment]
I still cannot see the Cloud Foundry app on my account. Is there a link to the flask app you created?

**Comment by hi348** [comment]
https://cloud.ibm.com/developer/appservice/apps/80f85e63-cc16-40b5-9caa-b44d4c481cac

**Comment by qijinze911** [comment]
I cannot open this link, it shows error and jump to my own link. Have you invite me, my ibm id is jq699@nyu.edu. Could you please try it?

**Comment by cheryl1223** [comment]
> I cannot open this link, it shows error and jump to my own link. Have you invite me, my ibm id is [jq699@nyu.edu](mailto:jq699@nyu.edu). Could you please try it?

me neither, and my ibm account is yx1885@nyu.edu

**Comment by hi348** [comment]
https://cloud.ibm.com/apps/4dcbeb72-0cad-4b73-9b01-26c568ff7a38?paneId=overview&ace_config=%7B%22region%22%3A%22us-south%22%2C%22crn%22%3A%22crn%3Av1%3Abluemix%3Apublic%3Acf%3Aus-south%3As%2F43f1c8f4-b537-47de-9ec2-e0bc1abf4f20%3A%3Acf-application%3A4dcbeb72-0cad-4b73-9b01-26c568ff7a38%22%2C%22resource_id%22%3A%224dcbeb72-0cad-4b73-9b01-26c568ff7a38%22%2C%22orgGuid%22%3A%224c50672d-cda1-4aa1-9260-2a0ea7d89a50%22%2C%22spaceGuid%22%3A%2243f1c8f4-b537-47de-9ec2-e0bc1abf4f20%22%2C%22redirect%22%3A%22https%3A%2F%2Fcloud.ibm.com%2Fresources%22%2C%22bluemixUIVersion%22%3A%22v6%22%7D&env_id=ibm:yp:us-south

Should work now. Make sure you are in my account when you try to access the resource list. If this still doesn't work someone should work with me in real time to resolve this. Worst case scenario I'll have someone else pick this up.

**Comment by cheryl1223** [comment]
it seems very strange that I can open the link after you sent it (around 1 am), but when I tried to access it again now it's always timeout. Should we have a meeting to discuss how to address this?

**Comment by cheryl1223** [comment]
it seems very strange that I can open the link after you sent it (around 1 am), but when I tried to access it again now it's always timeout. Should we have a meeting to discuss how to address this?

**Comment by hi348** [comment]
yes

**Comment by hi348** [comment]
I am on right now. Send me the hangout link and I will show you what I did to set it up and maybe you can point out what I did wrong.

**Comment by hi348** [comment]
You can send via this thread or slack.

**Comment by cheryl1223** [comment]
I’m sorry that I’m not feeling well today and was working at another project so cannot make the meeting today. Please reach out to Jinze as he is now looking at the cloudant configuration
