### ISSUE TITLE
Test SQLAlchemy on IBM Cloud

### ISSUE THREAD

**Issue by cheryl1223** [nyudevops-recommendation/recommendations#61]
**As a** developer
**I need** database on IBM Cloud for my application
**So that** I can store my data

**Assumptions:** 
* we are not sure if SQLAlchemy will work on IBM Cloud, if it doesn't work, we should use another database

**Acceptance Criteria:**
```
Given no change to the current database configuration based on SQLAlchemy
When deploying to IBM Cloud
Then the database is well set
```

**Comment by hi348** [comment]
There is no sqlalchemy option that I can see on IBM cloud. We probably just need to convert the code to use cloudant...

**Comment by cheryl1223** [comment]
that's fine, we can modify our codes according to the sample codes the professor provides
