### ISSUE TITLE
Set up ElephantSQL

### ISSUE THREAD

**Issue by cheryl1223** [nyudevops-recommendation/recommendations#62]
**As a** developer
**I need** database on IBM Cloud for my application
**So that** I can store and access (CRUD) my data on IBM Cloud

**Assumptions:** 
* The database we choose works well on IBM Cloud.

**Acceptance Criteria:**
```
After we finishing setting up on database IBM Cloud,
When deploying to IBM Cloud
Then the database is well set
```

**Comment by hi348** [comment]
For now I used elephant because it seemed easier than cloudant. We can try cloudant in the future if necessary.
